config/routes.rb
Rails.application.routes.draw do

  post 'public/upload_images/images'

  root 'images#index'

  resources :images
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base

	has_attached_file :avatar, styles: { small: "100x200", medium: "400x200>", thumb: "200x100>" , large: "600x300>"} ,url: '/upload_images/:class/:attachment/000/000/:id/:style/:filename'
	validates_attachment_size :avatar, :in => 0.kilobytes..200.kilobytes

    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
# validates_attachment_size :avatar, size: { in: 0..20.kilobytes }
# ,url: '/upload_images/:class/000/000/:attachment/:id/:style/:filename'

	# validates_attachment :avatar,
	# content_type: { content_type: ["image/jpeg", "image/gif", "image/png","image/jpg"] }



	# has_attached_file :avatar
	# validates_attachment_content_type :avatar, content_type: /\Aimage/
	# validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]
	# do_not_validate_attachment_file_type :avatar


#   text_plain = MIME::Types["text/plain"].first
# text_plain.extensions << "foo"
# MIME::Types.index_extensions text_plain

validates :title, presence: true, length: {minimum: 3}
validates :descrip, presence: true, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
        class ImagesController < ApplicationController
        
        
        # before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]
        
        def index
        @images= Image.all
        end
        def create
        @image = Image.create(image_params)
        if@image.save
        
        flash[:notice] = "Success Add Records"
        
        redirect_to action: 'index'
        
        else
        flash[:error] = "data not valid"
        
        render 'new'
        
        end
        
        end
        
        def new
        @image = Image.new
        end
        
        def edit
        @image=Image.find_by_id(params[:id])
        
        end
        
        def show
        @image=Image.find_by_id(params[:id])
        end
        
        def destroy
        
        @image =Image.find_by_id(params[:id])
        if @image.destroy
        flash[:notice] = "Succer delete "
        
        redirect_to action: 'index'
        else
        flash[:notice] = "fails delete a records "
        redirect_to action: 'index'
        
        end
        
        end
        def update
        @image=Image.find_by_id(params[:id])
        if @image.update(image_params)
        flash[:notice] = "Succes"
        redirect_to action: 'index'
        else
        flash[:notice] = "data not valid"
        render 'edit'
        
        
        end
        end
        
        private
        def image_params
        params.require(:image).permit(:avatar,:title,:descrip)
        end
        end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/edit.html.erb
    <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    
    <div class="container">

  <%= form_for @image, url: image_path, html: { multipart: true } do |form| %>
  <div class="form-group">
  <%= form.label :avatar , :class => 'control-label col-sm-2'%>
  <div class="col-sm-10">
  
  <%= form.file_field :avatar %>
  </div>
  </div>

  <div class="form-group">
  <%= form.label :title ,:class => 'control-label col-sm-2'%>  
  <div class="col-sm-10">
  <%= form.text_field :title %>
  <br/>
  </div>
  </div>
  <div class="form-group">
  
  <%= form.label 'Deskripsi' ,:class => 'control-label col-sm-2'%>
 

        <div class="col-sm-10">
        <%= form.text_area :descrip%>
        <br/>
        </div>
        </div>
        <div class="col-sm-offset-2 col-sm-10">
        <%= form.submit  'Upload' ,:class => 'btn btn-default' %>
        </div>
        <% end %>
        </div>

app/views/images/index.html.erb
	
	<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
	<% end %>
	
	<h2 style="text-align: center;">Gallery</h2>
	
	<div id="mantap" class="transition-enabled">
	<% @images.each do |image|%>

		<div class="box panel panel-default" >
		
		<%= link_to image_path(image.id) do %>
		<%=image_tag image.avatar.url()%>
		<%end%>

		<div class="panel-body">
		<h4><strong><%= image.title%></strong></h4>
		<hr/>
		<p>
		<%= image.descrip.truncate(20)%>
		</p>

	<%= link_to 'Edit' , edit_image_path(image.id)%>
	<%= link_to 'Remove' , image_path(image.id),method: "DELETE",data:{confirm: 'are you sure delete this data ?'} %>
	
	</div>
	</div>
	<%end%></div>
	
	

app/views/images/new.html.erb
    
    <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
    <% end %>

  <div class="container">
  
  <%= form_for @image, url: images_path, html: { multipart: true } do |form| %>
  <div class="form-group">
  <%= form.label 'chose file',:class => 'control-label col-sm-2'%>
  
  <div class="col-sm-10">
  <%= form.file_field :avatar %>
  </div>

<%= @image.errors[:avatar].first unless @image.errors[:avatar].blank? %>

</div>
  
  <div class="form-group">
  
  <%= form.label :title ,:class => 'control-label col-sm-2'%>
  
  <div class="col-sm-10">
  <%= form.text_field :title %>
  <br/>
  </div>
  <%= @image.errors[:title].first unless @image.errors[:title].blank? %>
  
  </div>

        <div class="form-group">
        
        <%= form.label 'Deskripsi' ,:class => 'control-label col-sm-2'%>
        
        
        <div class="col-sm-10">
        <%= form.text_area :descrip%>
        <br/>
        </div>
        <%= @image.errors[:descrip].first unless @image.errors[:descrip].blank? %>
        
        </div>
        <div class="col-sm-offset-2 col-sm-10">
        <%= form.submit  'Upload' ,:class => 'btn btn-default' %>
        </div>
        <% end %>
        </div>

app/views/images/show.html.erb
<div class="container">
 <div class="col-center">
<%= image_tag @image.avatar.url(:large) %>
<h2><%= @image.title%></h2>

<p>
	
<%= @image.descrip%>

</p>
</div>

</div>

app/views/layouts/_header.html.erb
    <!--bagian navigation-->
    <nav>
    <div class="navbar navbar-fixed-top navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
          </button>
          <a href=”#” class = "navbar-brand">Tugas 4</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
           <li> <%=link_to 'New Post', image_path('new') %></li>
          </ul>
        </div>  
      </div>
    </div>
</nav>
<div class="clearfix"></div>

app/views/layouts/application.html.erb
	<!DOCTYPE html>
	<html>
	<head>
	<style type="text/css">
	
	body{background-color: #F7F7F7 ;
	}
	
	</style>
	<title>Tugas4</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	</head>
	<body style="background-color:#ececec;">
	<%=render 'layouts/header'%>
	
	<%= yield %>
	
	

	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.2/masonry.pkgd.min.js"></script>
	</body>
	</html>